route:
 group_by: [cluster]
 receiver: alerts-test
 routes:
  - match:
      severity: slack
      receiver: alerts-test

receivers:
- name: alerts-test
  slack_configs:
  - api_url: https://hooks.slack.com/services/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 ### Change it with your URL
    channel: '#gowrisankark8s'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
